version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm install -g pnpm
      - pnpm pkg delete scripts.prepare
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm build
