version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm install -g pnpm
      - pnpm pkg delete scripts.prepare
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${DEPLOY_BUCKED}
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths /index.html
