export const ROUTES_PATH = {
  landingPage: '/',
  all: '*',
  login: '/login',
  clientRegister: '/cadastro-cliente',
  garageRegister: '/cadastro-garagem',
  consultaPlaca: '/consulta-placa',
  garageHome: '/garage',
  garageDashboard: '/garage/dashboard',
  addVeiculo: '/garage/add-veiculo',
  buggetsSearch: '/garage/orcamentos',
  bugget: '/garage/orcamento',
  clientHome: '/cliente',
  clientBudgets: '/cliente/orcamentos',
  clientTransfer: '/cliente/transferir',
};
