export const ROUTES_PATH = {
  landingPage: '/',
  all: '*',
  login: '/login',
  budgetWithoutLogin: '/orcamento',
  budgetApprovedWithoutLogin: '/orcamento-aprovado',
  budgetRejectedWithoutLogin: '/orcamento-rejeitado',
  clientRegister: '/cadastro-cliente',
  garageRegister: '/cadastro-garagem',
  consultaPlaca: '/consulta-placa',
  garageHome: '/garage',
  garageDashboard: '/garage/dashboard',
  garageAddVeiculo: '/garage/add-veiculo',
  garageBuggetSearch: '/garage/orcamentos',
  garageBudgetView: '/garage/orcamento',
  clientHome: '/cliente',
  clientBudgetSearch: '/cliente/orcamentos',
  clientBudgetView: '/cliente/orcamento',
  clientTransfer: '/cliente/transferir',
};
